# Generated by Django 2.2 on 2023-04-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('warnning_type', models.CharField(max_length=2)),
                ('good_type', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('descript', models.TextField()),
            ],
        ),
    ]
