# Generated by Django 2.2 on 2023-05-12 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gene', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gene.Property'),
        ),
    ]
