# Generated by Django 2.2 on 2023-04-16 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gene', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='title',
            field=models.ForeignKey(db_column='title', null=True, on_delete=django.db.models.deletion.CASCADE, to='Gene.Property'),
        ),
    ]
