# Generated by Django 2.2 on 2023-04-16 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gene', '0002_gene_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gene',
            name='title',
        ),
        migrations.AddField(
            model_name='gene',
            name='property_id',
            field=models.ForeignKey(db_column='property_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_id', to='Gene.Property'),
        ),
    ]
