# Generated by Django 2.2 on 2023-05-12 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gene', '0002_gene_property'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lifestyle',
        ),
    ]
