# Generated by Django 2.2 on 2023-05-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gene', '0005_auto_20230513_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gene',
            name='type',
        ),
        migrations.AddField(
            model_name='gene',
            name='good_type',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='gene',
            name='warnning_type',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
