# Generated by Django 2.2 on 2023-05-17 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gene', '0006_auto_20230516_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('feeling_rating', models.IntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')])),
                ('diary_image', models.ImageField(blank=True, upload_to='')),
                ('diary_image2', models.ImageField(blank=True, upload_to='')),
                ('diary_image3', models.ImageField(blank=True, upload_to='')),
                ('content', models.TextField()),
                ('dt_created', models.DateField(auto_now_add=True)),
                ('dt_updated', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
