# Generated by Django 4.2.1 on 2023-05-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gene', '0006_auto_20230516_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
