# Generated by Django 2.2 on 2023-05-21 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gene', '0009_auto_20230519_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='BDNF_gene',
        ),
        migrations.RemoveField(
            model_name='user',
            name='FTO_gene',
        ),
        migrations.RemoveField(
            model_name='user',
            name='MC4R_gene',
        ),
    ]
