# Generated by Django 2.2 on 2023-05-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gene', '0010_auto_20230521_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='BDNF_gene',
            field=models.IntegerField(choices=[(1, 'AA'), (2, 'AG'), (3, 'GG')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='FTO_gene',
            field=models.IntegerField(choices=[(1, 'TT'), (2, 'TA'), (3, 'AA')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='MC4R_gene',
            field=models.IntegerField(choices=[(1, 'TT'), (2, 'TC'), (3, 'CC')], default=None, null=True),
        ),
    ]
