# Generated by Django 2.2 on 2023-05-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gene', '0012_gene_middle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='MC1R_gene',
            field=models.IntegerField(choices=[(1, 'GG'), (2, 'GA'), (3, 'AA')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='OCA2_gene',
            field=models.IntegerField(choices=[(1, 'TT'), (2, 'TC'), (3, 'CC')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='chr20p11_1',
            field=models.IntegerField(choices=[(1, 'GG'), (2, 'GA'), (3, 'AA')], default=None, null=True),
        ),
    ]
