# Generated by Django 2.2 on 2023-05-22 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gene', '0012_gene_middle_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Fat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FTO_gene', models.IntegerField(choices=[(1, 'TT'), (2, 'TA'), (3, 'AA')], default=None, null=True)),
                ('MC4R_gene', models.IntegerField(choices=[(1, 'TT'), (2, 'TC'), (3, 'CC')], default=None, null=True)),
                ('BDNF_gene', models.IntegerField(choices=[(1, 'AA'), (2, 'AG'), (3, 'GG')], default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
