# Generated by Django 2.2 on 2023-05-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gene', '0013_auto_20230522_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ABCA1',
            field=models.IntegerField(choices=[(1, 'CC'), (2, 'CT'), (3, 'TT')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ABO',
            field=models.IntegerField(choices=[(1, 'CC'), (2, 'CA'), (3, 'AA')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='AGER_1',
            field=models.IntegerField(choices=[(1, 'CC'), (2, 'CT'), (3, 'TT')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='AGER_2',
            field=models.IntegerField(choices=[(1, 'GG'), (2, 'GA'), (3, 'AA')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='AHR',
            field=models.IntegerField(choices=[(1, 'CC'), (2, 'CT'), (3, 'TT')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ANGPTL3',
            field=models.IntegerField(choices=[(1, 'GG'), (2, 'GT'), (3, 'TT')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ATP2B1',
            field=models.IntegerField(choices=[(1, 'AA'), (2, 'AG'), (3, 'GG')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='CDKN2A_2B',
            field=models.IntegerField(choices=[(1, 'CC'), (2, 'CT'), (3, 'TT')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='CYP17A1',
            field=models.IntegerField(choices=[(1, 'GG'), (2, 'GA'), (3, 'AA')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='CYP1A1_CYP1A2',
            field=models.IntegerField(choices=[(1, 'AA'), (2, 'AC'), (3, 'CC')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='DGKB_TMEM195',
            field=models.IntegerField(choices=[(1, 'GG'), (2, 'GT'), (3, 'TT')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='EDAR',
            field=models.IntegerField(choices=[(1, 'GG'), (2, 'GA'), (3, 'AA')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='FGF5',
            field=models.IntegerField(choices=[(1, 'AA'), (2, 'AT'), (3, 'TT')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='GCK',
            field=models.IntegerField(choices=[(1, 'GG'), (2, 'GA'), (3, 'AA')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='GCKR',
            field=models.IntegerField(choices=[(1, 'CC'), (2, 'CT'), (3, 'TT')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='GLIS3',
            field=models.IntegerField(choices=[(1, 'GG'), (2, 'GA'), (3, 'AA')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='GUCY1A3',
            field=models.IntegerField(choices=[(1, 'AA'), (2, 'AC'), (3, 'CC')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='HLA_DQB1',
            field=models.IntegerField(choices=[(1, 'AA'), (2, 'AG'), (3, 'GG')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='HMGCR',
            field=models.IntegerField(choices=[(1, 'AA'), (2, 'AT'), (3, 'TT')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='IL2RA',
            field=models.IntegerField(choices=[(1, 'TT'), (2, 'TC'), (3, 'CC')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='LIPG',
            field=models.IntegerField(choices=[(1, 'TT'), (2, 'TG'), (3, 'GG')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='NPR3',
            field=models.IntegerField(choices=[(1, 'AA'), (2, 'AG'), (3, 'GG')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='SLC23A1_1',
            field=models.IntegerField(choices=[(1, 'CC'), (2, 'CT'), (3, 'TT')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='SLC23A1_2',
            field=models.IntegerField(choices=[(1, 'AA'), (2, 'AG'), (3, 'GG')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='TRIB1',
            field=models.IntegerField(choices=[(1, 'TT'), (2, 'TA'), (3, 'AA')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='chr20p11_2',
            field=models.IntegerField(choices=[(1, 'CC'), (2, 'CT'), (3, 'TT')], default=None, null=True),
        ),
    ]
