# Generated by Django 2.2 on 2023-05-22 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gene', '0014_auto_20230522_0546'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Fat',
        ),
    ]
